version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: Abc@123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
